// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ansoplyinterface1.h"

/////////////////////////////////////////////////////////////////////////////
// CAnsoplyinterface1

IMPLEMENT_DYNCREATE(CAnsoplyinterface1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAnsoplyinterface1 properties

/////////////////////////////////////////////////////////////////////////////
// CAnsoplyinterface1 operations
